Phonebook/Phonebook/Models/AddContactVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Phonebook.Models
{
    public class AddContactVM
    {
        public Contact Contact { get; set; }
        public List<SelectListItem> FriendRating { get; set; }
        public List<SelectListItem> StarPower { get; set; }

        public AddContactVM()
        {
            FriendRating = new List<SelectListItem>
            {
                new SelectListItem {Text="Acquaintence", Value="Acquaintence" },
                new SelectListItem {Text="Friends", Value="Friends" },
                new SelectListItem {Text="Pretty Tight", Value="Pretty Tight" },
                new SelectListItem {Text="Besties", Value="Besties" },
            };

            StarPower = new List<SelectListItem>
            {
                new SelectListItem {Text="0", Value="0" },
                new SelectListItem {Text="1", Value="1" },
                new SelectListItem {Text="2", Value="2" },
                new SelectListItem {Text="3", Value="3" },
                new SelectListItem {Text="4", Value="4" },
                new SelectListItem {Text="5", Value="5" },
            };
        }
    }
}

Phonebook/Phonebook/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Phonebook.Models
{
    public class Contact
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public int id { get; set; }
        public string FriendRating { get; set; }
        public int StarPower { get; set; }
    }
}

Phonebook/Phonebook/Models/ContactRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Phonebook.Models
{
    public class ContactRepository
    {
        private static List<Contact> _contacts { get; set; }

        static ContactRepository()
        {
            _contacts = new List<Contact>
            {
                new Contact {FirstName="Miranda", LastName="Lambert", PhoneNumber="8087548866", Email="ml@gmail.com", id=1, FriendRating="Acquaintence", StarPower=1 },
                new Contact {FirstName="Selena", LastName="Gomez", PhoneNumber="2126548899", Email="sg@gmail.com", id=2, FriendRating="Acquaintence", StarPower=1 },
                 new Contact {FirstName="Taylor", LastName="Swift", PhoneNumber="6542159945", Email="ts@gmail.com", id=2, FriendRating="Bff", StarPower=10 }
            };
        }

        public static List<Contact> GetAllContacts()
        {
            return _contacts;
        }

        public static Contact Get(int Id)
        {
            return _contacts.FirstOrDefault(c => c.id == Id);
        }

        public static void InsertContact(Contact newContact)
        {
            if (_contacts.Count() == 0)
            {
                newContact.id = 1;
                _contacts.Add(newContact);
            }
            else
            {
                newContact.id = _contacts.Max(m=>m.id) + 1;
                _contacts.Add(newContact);
            }
        }

        public static void DeleteContact(int id)
        {
            _contacts.RemoveAll(x => x.id == id);
        }

        public static void EditContact(Contact editedcontact)
        {
            _contacts.RemoveAll(x => x.id == editedcontact.id);
            _contacts.Add(editedcontact);
        }
    }
}

Phonebook/Phonebook/Controllers/ContactController.cs
using Phonebook.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Phonebook.Controllers
{
    public class ContactController : Controller
    {
        // Get  
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Add()
        {
            var model = new AddContactVM();
            model.Contact = new Contact();

            return View(model);
        }

        [HttpPost]
        public ActionResult PostContact(AddContactVM newContact)
        {
            ContactRepository.InsertContact(newContact.Contact);

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult DeleteContact(int id)
        {
            ContactRepository.DeleteContact(id);

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Edit (int id)
        {
            var model = ContactRepository.Get(id);

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit (Contact contact)
        {
            ContactRepository.EditContact(contact);

            return RedirectToAction("Index", "Home");
        }
    }
}

Phonebook/Phonebook/Views/Contact/Add.cshtml
@model Phonebook.Models.AddContactVM

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-xs-6">
        <form action="/Contact/PostContact" method="post">
            <div class="form-group">
                <label class="control-label">First Name</label>
                @Html.TextBoxFor(m=>m.Contact.FirstName, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label class="control-label">Last Name</label>
                @Html.TextBoxFor(m => m.Contact.LastName, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label class="control-label">Phone Number</label>
                @Html.TextBoxFor(m => m.Contact.PhoneNumber, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label class="control-label">Email</label>
                @Html.TextBoxFor(m => m.Contact.Email, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label class="control-label">Friend Rating</label>
                @Html.DropDownListFor(m => m.Contact.FriendRating, Model.FriendRating, "-SELECT-", new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label class="control-label">Star Power</label>
                @Html.DropDownListFor(m => m.Contact.StarPower, Model.StarPower, "-SELECT-", new { @class = "form-control" })
            </div>
            <button class="btn btn-primary">Save</button>
        </form>
    </div>
</div>
    

Phonebook/Phonebook/Views/Contact/Edit.cshtml
@model Phonebook.Models.Contact

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-xs-6">
        <h1>Edit Contact</h1>
        @using (Html.BeginForm("Edit", "Contact", FormMethod.Post))
        {
            <div class="form-group">
                @Html.LabelFor(m=>m.FirstName, new { @class="control-label"})
                @Html.TextBoxFor(m=>m.FirstName, new { @class="form-control"})
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.LastName, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.PhoneNumber, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Email, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.FriendRating, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.FriendRating, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.StarPower, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.StarPower, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.id, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.id, new { @class = "form-control" })
            </div>
            <button class="btn btn-primary">Save</button>
        }
    </div>
</div> 

Phonebook/Phonebook/Views/Contact/Index.cshtml
@model List<Phonebook.Models.Contact>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-xs-12">
        <div class="page-header">
            @Html.ActionLink("Add a contact", "Add", "Contact", new { @class = "btn btn-default" })
        </div>
        <h1>Contact List</h1>
        @if (Model.Any())
        {
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Phone Number</th>
                        <th>Email</th>
                        <th>Friend Rating</th>
                        <th>Star Power</th>
                        <th>Id</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var contact in Model)
                    {
                        <tr>
                            <td>@Html.ActionLink(contact.FirstName, "Edit", "Contact", new { id = contact.id }, null)</td>
                                        <td>@contact.LastName</td>
                                        <td>@contact.PhoneNumber</td>
                                        <td>@contact.Email</td>
                                        <td>@contact.FriendRating</td>
                                        <td>
                                            @for (int i = 0; i < contact.StarPower; i++)
                                        {
                                            <img src="~/Images/Star.jpg" />
                                        }
                                    </td>
                                    <td>@contact.id</td>
                                    <td>
                                        <form action="@Url.Action("DeleteContact", "Contact", new {id=@contact.id})" method="post">
                                            <button class="btn btn-danger" onclick="return confirm('Are you sure you want to delete @contact.FirstName @contact.LastName');">X</button>
                                        </form>
                                    </td>
                                </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>There are no contacts, go make some friends!</p>
        }
    </div>
</div>