MovieCatalog/MovieCatalog/Models/AddMovieVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieCatalog.Models
{
    public class AddMovieVM
    {
        public Movie Movie { get; set; }
        public List<SelectListItem> RatingList { get; set; }
        public List<SelectListItem> StarList { get; set; }

        public AddMovieVM()
        {
            RatingList = new List<SelectListItem>
            {
                new SelectListItem {Text="G", Value="G" },
                new SelectListItem {Text="PG", Value="PG" },
                new SelectListItem {Text="PG-13", Value="PG-13" },
                new SelectListItem {Text="R", Value="R" },
                new SelectListItem {Text="NC-17", Value="NC-17" }
            };

            StarList = new List<SelectListItem>
            {
                new SelectListItem {Text="0", Value="0" },
                new SelectListItem {Text="1", Value="1" },
                new SelectListItem {Text="2", Value="2" },
                new SelectListItem {Text="3", Value="3" },
                new SelectListItem {Text="4", Value="4" },
                new SelectListItem {Text="5", Value="5" }
            };
        }


    }
}

MovieCatalog/MovieCatalog/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MovieCatalog.Models
{
    public class Movie
    {
        public int MovieId { get; set; }
        public string Title { get; set; }
        public string Rating { get; set; }
        public int Stars { get; set; }
    }
}

MovieCatalog/MovieCatalog/Models/MovieRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MovieCatalog.Models
{
    public class MovieRepository
    {
        private static List<Movie> _movies;

        static MovieRepository()
        {
            _movies = new List<Movie>
            {
                new Movie {MovieId=1, Title="Ghostbusters", Rating="PG-13", Stars=4 },
                new Movie {MovieId=2, Title="Star Wars", Rating="PG", Stars=5 },
                new Movie {MovieId=3, Title="Aristocats", Rating="G", Stars=2 }
            };
        }

        public static List<Movie> GetAll()
        {
            return _movies;
        }

        public static Movie Get(int id)
        {
            return _movies.FirstOrDefault(m => m.MovieId == id);
        }

        public static void Insert(Movie movie)
        {
            movie.MovieId = _movies.Max(m => m.MovieId) + 1;
            _movies.Add(movie);
        }

        public static void Delete(int id)
        {
            _movies.RemoveAll(m => m.MovieId == id);
        }

        public static void Edit(Movie movie)
        {
            _movies.RemoveAll(m => m.MovieId == movie.MovieId);
            _movies.Add(movie);
        }
    }
}

MovieCatalog/MovieCatalog/Controllers/HomeController.cs
using MovieCatalog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieCatalog.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            var model = MovieRepository.GetAll();

            return View(model);
        }
    }
}

MovieCatalog/MovieCatalog/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MovieCatalog.Models;

namespace MovieCatalog.Controllers
{
    public class MovieController : Controller
    {
        // GET is the default
        [HttpGet] // don't need this because Get is the default but this should help me remember
        public ActionResult Add()
        {
            var model = new AddMovieVM();
            model.Movie = new Movie(); //Need to make sure the object is instantiated or else it's value will be null and the program will blow up

            return View(model);
        }

        [HttpPost]
        public ActionResult PostMovie(AddMovieVM newMovie)
        {
            MovieRepository.Insert(newMovie.Movie);

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            MovieRepository.Delete(id);

            return RedirectToAction("Index", "Home");
        }
        
        
        public ActionResult Edit(int id)
        {
            var model = MovieRepository.Get(id);

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Movie movie)
        {
            MovieRepository.Edit(movie);

            return RedirectToAction("Index", "Home");
        }

        //[HttpPost]
        //public ActionResult PostMovie(string Title, string Rating, int Stars)
        //{
        //    Movie newMovie = new Movie();
        //    newMovie.Title = Title;
        //    newMovie.Rating = Rating;
        //    newMovie.Stars = Stars;

        //    MovieRepository.Insert(newMovie);

        //    return RedirectToAction("Index", "Home");
        //}

        //[HttpPost]
        //public ActionResult PostMovie()
        //{
        //    Movie newMovie = new Movie();
        //    newMovie.Title = Request.Form["Title"];
        //    newMovie.Rating = Request.Form["Rating"];
        //    newMovie.Stars = int.Parse(Request.Form["Stars"]);

        //    MovieRepository.Insert(newMovie);

        //    return RedirectToAction("Index", "Home");
        //}
    }
}

MovieCatalog/MovieCatalog/Views/Home/Index.cshtml
@model List<MovieCatalog.Models.Movie>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
      <div class="row">
        <div class="col-xs-6">
            @Html.BeginForm("PostMovie","Movie",FormMethod.Post)
        <h1>Movie List</h1>
            @Html.ActionLink("Add a movie", "Add", "Movie")

            @if(Model.Any())
            { 
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Rating</th>
                        <th>Stars</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var movie in Model)
                    {
                        <tr>
                            <td>@Html.ActionLink(movie.Title, "Edit", "Movie", new { id = movie.MovieId }, new { @class = "warning", @title = movie.Title + ":" + movie.Rating })</td>
                            <td>@movie.Rating</td>
                            <td>@for (int i = 0; i<movie.Stars; i++)
                                {
                                    <img src="~/Img/Star.jpg" />
                                }
                            </td>
                            <td>
                                <form action="@Url.Action("Delete", "Movie", new { id = @movie.MovieId })" method="post">
                                    <button class="btn btn-danger" onclick="return confirm('Are you sure you want to delete @movie.Title');">X</button>
                                    @Html.AntiForgeryToken()                                
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            }
            else
            {
                <p>You have no movies, sad face.</p>
            }

            @Html.Partial("_Actor")
            </div>
        </div>
@section scripts{
    <script>
        alert("Hello!");
    </script>
            
    }
@section header{
    <h1>SG Movie Catalogue</h1>
    }

MovieCatalog/MovieCatalog/Views/Home/Index3.cshtml
@model MovieCatalog.Models.Movie
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section header{
    <h1>SG Movie Catalog</h1>
}

<div class="row">
    <div class="col-xs-12">
        <p id="ImportantText" class="warning">
            It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
        </p>

    </div>
</div>